--------------------------------------------------------
-- Archivo creado  - viernes-mayo-23-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMERCIANTE
--------------------------------------------------------

  CREATE TABLE "DESARROLLADOR"."COMERCIANTE" 
   (	"ESTADO" BOOLEAN, 
	"FECHA_REGISTRO" DATE, 
	"FECHA_ACTUALIZACION" TIMESTAMP (6), 
	"ID" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USUARIO_ACTUALIZACION_ID" NUMBER(19,0), 
	"CORREO_ELECTRONICO" VARCHAR2(255 CHAR), 
	"MUNICIPIO" VARCHAR2(255 CHAR), 
	"NOMBRE_RAZON_SOCIAL" VARCHAR2(255 CHAR), 
	"TELEFONO" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008526
--------------------------------------------------------

  CREATE UNIQUE INDEX "DESARROLLADOR"."SYS_C008526" ON "DESARROLLADOR"."COMERCIANTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMERCIANTE
--------------------------------------------------------

  ALTER TABLE "DESARROLLADOR"."COMERCIANTE" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "DESARROLLADOR"."COMERCIANTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DESARROLLADOR"."COMERCIANTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMERCIANTE
--------------------------------------------------------

  ALTER TABLE "DESARROLLADOR"."COMERCIANTE" ADD CONSTRAINT "FK8AVG3KGEKWQ9UOYA5RNG2CWIB" FOREIGN KEY ("USUARIO_ACTUALIZACION_ID")
	  REFERENCES "DESARROLLADOR"."USUARIO" ("ID") ENABLE;
